version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  coveralls: coveralls/coveralls@1.0.4

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler:2.1.4
      - run:
          name: Install dependencies with bundler
          command: bundle install
      - run:
          name: Run tests
          command: bundle exec rspec
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov/project.lcov

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - circle
