version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler:2.1.4
      - run:
          name: Install dependencies with bundler
          command: BUNDLE_PATH=vendor/bundle bundle install
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - circle
