name: Test Coveralls
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      NODE_COVERALLS_DEBUG: 1
      SSL_CERT_DIR: /etc/ssl/certs
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.7
        bundler-cache: false
    
    - name: Run tests
      run: bundle install && bundle exec rspec
    
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coveralls-endpoint: https://coveralls:alpha@covervlad.fly.dev
        path-to-lcov: ./coverage/lcov/coveralls-demo-ruby.lcov
